# Generated by Django 5.2.6 on 2025-12-19 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyExpNotifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('notified_at', models.DateTimeField(verbose_name='Notified At')),
            ],
            options={
                'verbose_name': 'Key Expiration Notification',
                'verbose_name_plural': 'Key Expiration Notifications',
            },
        ),
        migrations.CreateModel(
            name='KeyTraffic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('upload_mb', models.PositiveBigIntegerField(default=0, verbose_name='Uploaded (MB)')),
                ('download_mb', models.PositiveBigIntegerField(default=0, verbose_name='Downloaded (MB)')),
                ('total_mb', models.PositiveBigIntegerField(default=0, verbose_name='Total (MB)')),
            ],
            options={
                'verbose_name': 'Key Traffic',
                'verbose_name_plural': 'Key Traffics',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('end_date', models.DateTimeField(verbose_name='Expiration Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Auto Renew')),
                ('servers', models.ManyToManyField(related_name='keys', to='server.server', verbose_name='Server')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tariff.tariff', verbose_name='Tariff')),
            ],
            options={
                'verbose_name': 'Key',
                'verbose_name_plural': 'Keys',
            },
        ),
    ]
