# Generated by Django 5.2.6 on 2025-12-19 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('key', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='keyexpnotifications',
            name='key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exp_notification', to='key.key', verbose_name='Key'),
        ),
        migrations.AddField(
            model_name='keytraffic',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic', to='key.key', verbose_name='Key'),
        ),
    ]
