# Generated by Django 5.2.6 on 2025-12-19 08:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('domain', models.CharField(max_length=255, verbose_name='Domain')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'DNS record',
                'verbose_name_plural': 'DNS records',
            },
        ),
    ]
