# Generated by Django 5.2.6 on 2025-12-19 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('key_id', models.UUIDField(verbose_name='Key ID')),
                ('upload_mb', models.PositiveBigIntegerField(default=0, verbose_name='Upload (MB')),
                ('download_mb', models.PositiveBigIntegerField(default=0, verbose_name='Download (MB)')),
                ('total_mb', models.PositiveBigIntegerField(default=0, verbose_name='Total (MB)')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='server.server', verbose_name='Server')),
            ],
            options={
                'verbose_name': 'Traffic Usage',
                'verbose_name_plural': 'Traffic Usages',
                'indexes': [models.Index(fields=['key_id', 'server'], name='traffic_tra_key_id_1ef76f_idx')],
            },
        ),
    ]
