# Generated by Django 5.2.6 on 2025-12-19 08:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Title')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('api_url', models.URLField(verbose_name='API URL')),
                ('api_user', models.CharField(max_length=255, verbose_name='API user')),
                ('api_key', models.CharField(max_length=255, verbose_name='API key')),
                ('do_setup', models.BooleanField(default=True, verbose_name='Needs Setup. (All inbounds will be deleted and recreated)')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
    ]
