# Generated by Django 5.2.6 on 2025-12-19 08:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('message_id', models.CharField(blank=True, null=True, verbose_name='Message ID')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Cancelled')),
                ('do_cancel', models.BooleanField(default=False, verbose_name='Do Cancel')),
            ],
            options={
                'verbose_name': 'Telegram payment',
                'verbose_name_plural': 'Telegram payments',
            },
        ),
    ]
